---
version: '2'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 32181:2181
  
  kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2

    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 39092:39092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-3:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 49092:49092
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092,PLAINTEXT_HOST://localhost:49092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  init-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka-3:9092 --list
      
      echo -e 'Creating kafka bevents-streaming-aggregate-first-salary '
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev__bevents__realtime__aggregate_first_salary__dlq --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev_bevents__realtime__enrichment_first_salary_transactions__uaspdto --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev_bevents__realtime__aggregate_first_salary__uaspdto --replication-factor 1 --partitions 3
  
  
      echo -e 'Creating kafka topics'
      #kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev_input_converter_cardfl_refill_uasp_dlq --replication-factor 1 --partitions 3
      #kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev_input_converter_cardfl_refill_uasp --replication-factor 1 --partitions 3
      #kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev_bevents_udds_mdm_rate_case68_uaspdto_dlq --replication-factor 1 --partitions 3
      #kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev_bevents_cft_way4_profile_udds_before_mdm_rate_case68_uaspdto --replication-factor 1 --partitions 3
      #kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev_bevents_cft_way4_profile_udds_before_case68_uaspdto --replication-factor 1 --partitions 1
      
      #uasp-streaming-mdm-enrichment case-68_agrement
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev_rto_batch_ca_customer_card68_uaspdto_dlq --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev__dko_uasp__card_agreement_converted --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev_bevents_cft_way4_profile_udds_before_case68_uaspdto_dlq --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev_bevents_cft_way4_profile_udds_before_case68_uaspdto --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev_bevents_udds_mdm_rate_case68_uaspdto --replication-factor 1 --partitions 3
      
      #uasp-streaming-mdm-enrichment case-68_agrement
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev_bevent__batch__ca_regulatory_client_id_of_profile__json_dlq --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic profile_tx_out --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev_bevents__batch__ca_regulatory_client_id_of_profile__json_converted --replication-factor 1 --partitions 3
      
      #module-vector
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev_bevents__realtime__filter_first_salary__uaspdto --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev_bevents__realtime__modelvector_first_salary__qa --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev__rto_uasp__case_39_old --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev__rto_uasp__case_39_vector --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev__rto_uasp__case_44 --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev__rto_uasp__case_48 --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev__rto_uasp__case_51 --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev__rto_uasp__case_71 --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev__rto_uasp__izost --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev__rto_uasp__pdscp --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev__rto_uasp__pks --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev__rto_uasp__ppnsx --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev__rto_uasp__zp --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev__rto_uasp__zzp --replication-factor 1 --partitions 3
      
      #uasp-streaming-input-convertor
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev_bevents__batch__ca_regulatory_client_id_of_profile__json --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev_bevents__batch__ca_regulatory_client_id_of_profile__json_converted --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-3:9092 --create --if-not-exists --topic dev_bevent__batch__ca_regulatory_client_id_of_profile__json_dlq --replication-factor 1 --partitions 3
      
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka-3:9092 --list
      "
  db:
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    image: postgres:12.11
    #    restart: always
    environment:
      - POSTGRES_DB=db_configuration_manager
      - POSTGRES_USER=db_configuration_manager_admin
      - POSTGRES_PASSWORD=SNgCjskqMY8LqSvNZ_Y
    #      - POSTGRES_USER=postgres
    #      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql_12_11/data
volumes:
  db:
    driver: local