version: '2.1'
services:
  jobmanager:
    image: flink:1.12.1-scala_2.12
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: localhost
    network_mode: "host"
  taskmanager:
    image: flink:1.12.1-scala_2.12
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: localhost
        taskmanager.numberOfTaskSlots: 10
    network_mode: "host"
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    network_mode: "host"
  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://:9094,OUTSIDE://localhost:9092
      - KAFKA_LISTENERS=INSIDE://:9094,OUTSIDE://:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
      - KAFKA_CREATE_TOPICS="user_behavior:1:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"

