version: '3.3'
services:
  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass qwerty123
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local